#!/bin/sh
# $Id: vas_sm 328 2010-10-22 02:51:55Z yamamoto2 $

# Copyright (c) 2010 VA Linux Systems Japan K.K. All rights reserved.
#
# LICENSE NOTICE
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the Company nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COMPANY AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COMPANY OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# chkconfig: 2345 99 99
# description:  Starts and stops storage manager

. /etc/init.d/functions

STORAGE_MANAGER_BIN=/opt/vas/bin

RETVAL=0

start()
{
	[ -x ${STORAGE_MANAGER_BIN}/daemon_launcher ] || exit 5
	[ -x ${STORAGE_MANAGER_BIN}/storage_manager ] || exit 5
	[ -x ${STORAGE_MANAGER_BIN}/check_servers ] || exit 5

	[ -f /var/run/vas_sm.run ] && exit 0	# return success if already running for heartbeat

	${STORAGE_MANAGER_BIN}/daemon_launcher -a ${STORAGE_MANAGER_BIN}/storage_manager /var/run/vas_sm.run
	RETVAL=$?
	[ $RETVAL -eq 0 ] && ${STORAGE_MANAGER_BIN}/daemon_launcher -n 1 ${STORAGE_MANAGER_BIN}/check_servers /var/run/check_servers.run
	RETVAL=$?
}

stop()
{
	killproc -p /var/run/check_servers.run
	rm -f /var/run/check_servers.run
	killproc -p /var/run/vas_sm.run
	rm -f /var/run/vas_sm.run
	RETVAL=0
}

case "$1" in
  init)
	[ -x ${STORAGE_MANAGER_BIN}/vas_db ] || exit 5
	if [ -f /var/run/vas_sm.run ] ; then
		RETVAL=1
	else
		${STORAGE_MANAGER_BIN}/vas_db
		RETVAL=$?
	fi
	;;
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	if [ -f /var/run/vas_sm.run ] ; then
	    RETVAL=0
	else
	    RETVAL=1
	fi
	;;
  restart)
	stop
	start
	;;
  shutdown)
	if [ -f /var/run/vas_sm.run ] ; then
		${STORAGE_MANAGER_BIN}/shutdownAll
		RETVAL=$?
	else
		RETVAL=1
	fi
	[ $RETVAL -eq 0 ] && $0 stop
	;;
  *)
	echo $"Usage: vas_sm {start|stop|status|restart|shutdown}"
	RETVAL=3
	;;
esac

exit $RETVAL
