#!/bin/sh

# Copyright (c) 2010 VA Linux Systems Japan K.K. All rights reserved.
#
# LICENSE NOTICE
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the Company nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COMPANY AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COMPANY OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# chkconfig: 2345 99 99
# description:  Starts and stops storage server

. /lib/lsb/init-functions

STORAGE_MANAGER_BIN=/opt/vas/bin
RETVAL=0

case "$1" in
  start)
	[ -x ${STORAGE_MANAGER_BIN}/ssvr_reporter ] || exit 5
	if [ -f /var/run/ssvr_agent.run ] ; then
		RETVAL=1
	else
		${STORAGE_MANAGER_BIN}/ssvr_reporter -d
		RETVAL=$?
	fi
	;;
  stop)
	if [ -f /var/run/ssvr_reporter.run ] ; then
		killproc -p /var/run/ssvr_reporter.run ${STORAGE_MANAGER_BIN}/ssvr_reporter
	fi
	killproc -p /var/run/ssvr_agent.run ${STORAGE_MANAGER_BIN}/daemon_launcher
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/run/ssvr_agent.run
	killproc -p /var/run/DiskPatroller.run ${STORAGE_MANAGER_BIN}/daemon_launcher
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/run/DiskPatroller.run
	;;
  status)
	if [ -f /var/run/ssvr_agent.run ] ; then
	    RETVAL=0
	else
	    RETVAL=1
	fi
	;;
  refresh)
	[ -x ${STORAGE_MANAGER_BIN}/ssvr_reporter ] || exit 5
	${STORAGE_MANAGER_BIN}/ssvr_reporter -r
	RETVAL=$?
	;;
  *)
	echo $"Usage: vas_ssvr {start|stop|status|refresh}"
	RETVAL=3
	;;
esac

exit $RETVAL
